### ISSUE TITLE
You have a dramatic mistake in your documentation about mocking entity DBset

### ISSUE THREAD

**Issue by asartem** [aspnet/EntityFramework.Docs.ru-ru#12]
why don't you take your attention on such importan thing like GetEnumerator which should called as Func here:

  mockSet.As&lt;IQueryable&lt;Blog&gt;&gt;().Setup(m =&gt; m.GetEnumerator()).Returns(  ()=&gt;  data.GetEnumerator());
instead of your wrong implemenration 
  mockSet.As&lt;IQueryable&lt;Blog&gt;&gt;().Setup(m =&gt; m.GetEnumerator()).Returns(data.GetEnumerator());

Because Returns(data.GetEnumerator()); will reach end of collection after first loop and each next request to collection will return empty result!

**Comment by CeciAc** [comment]
Hello, @asartem 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
**Can you please provide the URL where you found this error?**

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @asartem 
 
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @asartem 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team

**Comment by asartem** [comment]
Hello. Sorry for the delay. I don't read GitHub messages :) 
https://docs.microsoft.com/en-us/ef/ef6/fundamentals/testing/mocking 
here is the post.
