### ISSUE TITLE
Некачественный перевод

### ISSUE THREAD

**Issue by ivanovevgeny** [aspnet/EntityFramework.Docs.ru-ru#13]
На странице переведены многие слова, которые переводить не нужно

Database. ексекутесклкомманд 
дбконтексттрансактион
трансактионскопеасинкфловоптион
...

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: e7e17e30-4349-3193-01f1-5eb33cb88546
* Version Independent ID: dcb6d719-ffc2-2796-c82c-b9873b74cb76
* Content: [Работа с транзакциями — EF6](https://docs.microsoft.com/ru-ru/ef/ef6/saving/transactions#feedback)
* Content Source: [entity-framework/ef6/saving/transactions.md](https://github.com/aspnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/ef6/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by srvbpigh** [comment]
Hello, @ivanovevgeny
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @ivanovevgeny
Здравствуйте, @<имя участника на GITHUB>! 
Благодарим Вас за участие. Наши специалисты могут отвечать только на отзывы по документации. 
Чтобы оставить отзыв по продукту, воспользуйтесь кнопкой «Оставить отзыв о продукте» внизу страницы портала документации. 
А по текущему каналу Вы можете оставлять любые отзывы, связанные с документацией. 
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by divega** [comment]
@CeciAc If I understand correctly, the feedback from @ivanovevgeny is about the translation of the documentation, but you closed with a template saying you can only respond to feedback on the documentation and not on product.

**Comment by ivanovevgeny** [comment]
@divega you're right, but i created #14 for this already.

**Comment by CeciAc** [comment]
My mistake @divega 
Thanks creating the PR @ivanbasov we'll better work on it from there

kind regards
