### ISSUE TITLE
Не работает пример.

### ISSUE THREAD

**Issue by Metalstyle** [aspnet/EntityFramework.Docs.ru-ru#16]
Не работает. Видео по ссылке
[Введите отзыв здесь]
https://youtu.be/VXtL_rY4Gv8

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 7ac57b24-45aa-e679-6ff9-5a25c369c1ff
* Version Independent ID: cc576199-b14c-a135-2291-cc48bf301b4e
* Content: [Начало работы — EF Core](https://docs.microsoft.com/ru-ru/ef/core/get-started/index?tabs=netcore-cli)
* Content Source: [entity-framework/core/get-started/index.md](https://github.com/aspnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/core/get-started/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @Metalstyle
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/EntityFramework.Docs #2043](https://github.com/aspnet/EntityFramework.Docs/issues/2043) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Здравствуйте, @Metalstyle!  

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией.  

Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/aspnet/EntityFramework.Docs/issues/2043.  

Мы очень ценим Ваш вклад в наши статьи.   

С наилучшими пожеланиями,  
Международная команда поддержки документации Майкрософт
